repos:
-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: 'v11.0.1'
    hooks:
    -   id: clang-format
-   repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.10
    hooks:
    - id: cmake-format
    # - id: cmake-lint
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.0.0'
    hooks:
    -   id: check-case-conflict
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
